
people_detection_config: configs/project_la/people_cars_detector.yaml
people_processing_config_path: configs/project_la/people
people_detection_models_path: models/general

focal_length_mm: 8
# focal_length_mm: 28
sensor_ratio: 0.00345
skip_frames: 4
im_width: 4104  
im_height: 3004
# im_width: 2448
# im_height: 2048

latitude: 28.619167
longitude: -81.524167
altitude: 0
heading: 2