infer_imgsize: 2048
drone_width_meters: 0.221
model_name: best.pt
model_conf: 0.4
model_num_workers: 8
model_augment: False
tile_size: 640
tile_overlap: 150
non_max_suppression_intersection_over_union_threshold: 0.01
bg_gradient_general_drop_percentile: 99
bg_gradient_bbox_expand_fraction: 2.2
bg_gradient_lower_bound_fraction_of_mean: 1.2
bg_gradient_higher_bound_fraction_of_mean: 1.3
bg_gradient_max_conf_increase: 0.3
bg_gradient_max_conf_decrease: 0.15
tracker_bbox_expand_fraction: 1.2
tracker_frame_edge_drop_margin_pix: 5
general_conf_threshold: 0.5