tracker_type: botsort
track_high_thresh: 0.4
track_low_thresh: 0.05

new_track_thresh: 0.35
track_buffer: 14
match_thresh: 0.8

gmc_method: none

proximity_thresh: 0.5
appearance_thresh: 0.25
with_reid: False
