model_name: yolo11m_custom
# model_name: yolo11m
nms: 0.1
levels:
  - name: 3
    params:
      nms_local: 0.1
      nms_global: 0.1
      scale: 1.0
      batch_size: 4
      conf: 0.05
      crop_x: 0.26
      overlap_x: 0.0
      crop_y: 0.31
      overlap_y: 0.0
      crop_global:
        t: 0.35
        b: 0.65
        l: 0.0
        r: 1.0
  - name: 2
    params:
      nms_local: 0.1
      nms_global: 0.1
      scale: 0.5
      batch_size: 1
      conf: 0.1
      crop_x: 0.51
      overlap_x: 0.0
      crop_y: 0.61
      overlap_y: 0.0
      crop_global:
        t: 0.2
        b: 1.0
        l: 0.8
        r: 1.0
  - name: 1
    params:
      nms_local: 0.1
      nms_global: 0.1
      scale: 0.25
      batch_size: 1
      conf: 0.1
      crop_x: 1.0
      overlap_x: 0.0
      crop_y: 1.0
      overlap_y: 0.0
      crop_global:
        t: 0.0
        b: 1.0
        l: 0.0
        r: 1.0
