data:
  train:
    images_path: data/pascal_part/images/
    labels_path: data/pascal_part/train_val_split/train
  val:
    images_path: data/pascal_part/images/
    labels_path: data/pascal_part/train_val_split/val
    use_augs: False
  
  labels_to_idx: configs/person_labels_small_set7.json
  labels_change_class: configs/full_labels_to_set7.json
  batch_size: 32
model:
  model_name: Unet
  backbone: resnext50_32x4d
  encoder_weights: imagenet
  encoder_freeze: False
  loss: focal
  optimizer:
    name: adam
    params:
      lr: 0.001
train:
  run_name: resnext50_32x4d-set7-full-dataset
  trainer:
    log_every_n_steps: 10
    max_epochs: 50
    precision: 16-mixed